baseURL = "https://script.izyx.xyz/"
languageCode = "zh-cn"
title = "稻米鼠的油猴脚本们"
author = "稻米鼠"

Copyright = "稻米鼠 All rights reserved."

publishdir = "docs"

[params]
  logo      = "/images/logo.jpg"
[params.navs]
  home = "/"
  qa = "/question-and-answer/"